### ISSUE TITLE
FYI-OSX-org-protocol setup without an additional server

### ISSUE THREAD

**Issue by yveszoundi** [tamouse/emacs_org_protocol_server#2]
Did you give another shot at setting up `org-protocol` on OSX without an relying on an external server?

I was successful with `org-protocol` setup on the Mac (El Capitan - 10.11.3) with Google Chrome, despite following some of the outdated instructions on the web. I use emacs from the terminal in _daemon mode_ and most of my work is via `emacsclient` within `tmux` sessions.

Below are the steps that I _recall_ following without much trouble:

**Step 1**
I used the [Org Capture chrome extension](https://chrome.google.com/webstore/detail/org-capture/kkkjlfejijcjgjllecmnejhogpbcigdc).

**Step 2**
I created an `EmacsClientCapture.app` application from the script editor:
- Export as application
- No code signing

The contents of the script were copied from this [jcardente blog post](http://jcardente.blogspot.ca/2010/09/saving-weblinks-to-org-mode-from-safari.html).
```
on open location this_URL
   do shell script 
      "/Applications/Emacs.app/Contents/MacOS/bin/emacsclient " & this_URL
end open location
```

In the `Info.plist` of the newly created application the following is set before the final `</dict></plist>` tags.

```xml
        <key>CFBundleIdentifier</key>
        <string>com.mycompany.AppleScript.EmacsClientCapture</string>
        <key>CFBundleURLTypes</key>
        <array>
            <dict>
                <key>CFBundleURLName</key>
                <string>EmacsClientCapture</string>
                <key>CFBundleURLSchemes</key>
                <array>
                    <string>org-protocol</string>
                </array>
            </dict>
        </array>
```
**Step 3**
I required few libraries in my `.emacs`.
```emacs-lisp
(mapc #'require '(org-protocol org-mac-link))
```

The relevant `org-capture` templates entries contain the following lines:
```emacs-lisp
               ("p" "Protocol" entry (file+headline org-ers-notes-file "Inbox")
                "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")

               ("L" "Link" entry (file+headline org-ers-notes-file "Links")
                "* %^{Title}\nSource: %u, %c\n \n%?")
```

**Comment by CestDiego** [comment]
This is super helpful thanks! :) @yveszoundi but my emacs distribution came without an `emacsclient` binary inside that path.
